### PR TITLE
GWT-715: add documentation for CanvasMapAddon

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
+1 : binding

**Comment by oliverm-be** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Vote count:
Jan De Moerloose: +1: binding
Olver May: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
