### PR TITLE
GWT-716: add jsonIgnore to ClientWmsLayer; otherwise there is print s…

### PR DESCRIPTION
**Pull request by janvenstermans**
…erialization error

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
+1 (binding)

**Comment by oliverm-be** [comment]
+1 (binding)

**Comment by pieterdg** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Vote count:
Jan De Moerloose: +1: binding
Oliver May: +1 (binding)
Pieter De Graef: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
